//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASIGNATURA()
        {
            this.GRUPODETALLE = new HashSet<GRUPODETALLE>();
            this.HORARIO = new HashSet<HORARIO>();
        }
    
        public int IDASIGNATURA { get; set; }
        public string ASIGNATURADESCRIPCION { get; set; }
        public string RAMADESCRIPCION { get; set; }
        public Nullable<int> IDPROFESORASIGNADO { get; set; }
        public Nullable<int> ESTATUS_C { get; set; }
        public Nullable<int> CREADOR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPODETALLE> GRUPODETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO> HORARIO { get; set; }
    }
}
