//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATALOGO()
        {
            this.CATALOGODETALLE = new HashSet<CATALOGODETALLE>();
        }
    
        public int CATALOGOID { get; set; }
        public string CATALOGODESCRIPCION { get; set; }
        public bool CATALOGOACTIVO { get; set; }
        public string OWNER { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGODETALLE> CATALOGODETALLE { get; set; }
    }
}
