//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPODETALLE
    {
        public int ID { get; set; }
        public int IDASIGNATURA { get; set; }
        public int IDGRUPO { get; set; }
        public int ESTATUS_C { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
        public string CREADOR { get; set; }
        public string D1 { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual GRUPO GRUPO { get; set; }
    }
}
