//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO()
        {
            this.GRUPODETALLE = new HashSet<GRUPODETALLE>();
        }
    
        public int IDGRUPO { get; set; }
        public string GRUPONUMERO { get; set; }
        public string GRUPODESCRIPCION { get; set; }
        public Nullable<int> IDUSUARIO_TUTOR { get; set; }
        public Nullable<int> IDUSUARIO_ORIENTADOR { get; set; }
        public string CICLO { get; set; }
        public string DESCRIPCION { get; set; }
        public string TURNO { get; set; }
        public Nullable<byte> ESTATUS { get; set; }
        public Nullable<int> ESTATUS_C { get; set; }
        public string CREADOR { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GRUPODETALLE> GRUPODETALLE { get; set; }
    }
}
