//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int IDHORARIO { get; set; }
        public Nullable<System.TimeSpan> HORAINICIO { get; set; }
        public Nullable<System.TimeSpan> HORAFINAL { get; set; }
        public Nullable<int> IDDIA { get; set; }
        public Nullable<int> IDASIGNATURA { get; set; }
        public int IDSALON { get; set; }
        public int ESTATUS_C { get; set; }
        public string OWNER { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
    
        public virtual ASIGNATURA ASIGNATURA { get; set; }
        public virtual SALON SALON { get; set; }
    }
}
