//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGMSG
    {
        public int IDLOGMSG { get; set; }
        public string IP { get; set; }
        public string LOCATION { get; set; }
        public string OS_BROWSER { get; set; }
        public string FUNCTION_METHOD { get; set; }
        public string MODULE { get; set; }
        public string OWNER { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
        public string DETAIL { get; set; }
    }
}
