//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALON()
        {
            this.HORARIO = new HashSet<HORARIO>();
        }
    
        public int IDSALON { get; set; }
        public string NOMBRESALON { get; set; }
        public string NOMBREEDIFICIO { get; set; }
        public string REFERENCIAS { get; set; }
        public int ESTATUS_C { get; set; }
        public string OWNER { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public System.DateTime DATEUPDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO> HORARIO { get; set; }
    }
}
