//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVServices.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int IDUSUARIO { get; set; }
        public string USUARIONAME { get; set; }
        public string CONTRASENIA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public string IMGUSER { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public string EMAIL { get; set; }
        public string EMAILALTERNO { get; set; }
        public string CP { get; set; }
        public string CALLE { get; set; }
        public string NUMEROINTERIOR { get; set; }
        public string NUMEROEXTERIOR { get; set; }
        public string D_MNPIO { get; set; }
        public string D_CIUDAD { get; set; }
        public string D_ESTADO { get; set; }
        public string D_TIPO_ASENTA { get; set; }
        public string D_ASENTA { get; set; }
        public string REFERENCIADOMICILIO { get; set; }
        public string TELCASA { get; set; }
        public string TELMOVIL { get; set; }
        public string TELOTRO { get; set; }
        public Nullable<System.DateTime> ANIONACIMIENTO { get; set; }
        public int TIPOUSUARIO_C { get; set; }
        public int ESTATUS_C { get; set; }
        public string MATRICULAESCOLAR { get; set; }
        public string OWNER { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
        public string D1 { get; set; }
        public string D2 { get; set; }
        public string D3 { get; set; }
    }
}
